// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LinkOnTitleScreen","status":true,"description":"presave plugin","parameters":{"URL":"https://distrokid.com/hyperfollow/isitjosh/joshville"}}
];
